/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_let_tok = 1,
  anon_sym_EQ = 2,
  aux_sym_expr_token1 = 3,
  aux_sym_apply_token1 = 4,
  anon_sym_COMMA = 5,
  sym_number = 6,
  sym_ident = 7,
  sym_string = 8,
  sym_source_file = 9,
  sym_toplevel = 10,
  sym_decl = 11,
  sym_expr = 12,
  sym_apply = 13,
  sym_concat = 14,
  sym_factor = 15,
  aux_sym_source_file_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_let_tok] = "let_tok",
  [anon_sym_EQ] = "=",
  [aux_sym_expr_token1] = "expr_token1",
  [aux_sym_apply_token1] = "apply_token1",
  [anon_sym_COMMA] = ",",
  [sym_number] = "number",
  [sym_ident] = "ident",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_toplevel] = "toplevel",
  [sym_decl] = "decl",
  [sym_expr] = "expr",
  [sym_apply] = "apply",
  [sym_concat] = "concat",
  [sym_factor] = "factor",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_let_tok] = sym_let_tok,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_expr_token1] = aux_sym_expr_token1,
  [aux_sym_apply_token1] = aux_sym_apply_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_number] = sym_number,
  [sym_ident] = sym_ident,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_toplevel] = sym_toplevel,
  [sym_decl] = sym_decl,
  [sym_expr] = sym_expr,
  [sym_apply] = sym_apply,
  [sym_concat] = sym_concat,
  [sym_factor] = sym_factor,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_let_tok] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expr_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_apply_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_toplevel] = {
    .visible = true,
    .named = true,
  },
  [sym_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_apply] = {
    .visible = true,
    .named = true,
  },
  [sym_concat] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '.') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(1);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 6:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_let_tok);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_expr_token1);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_apply_token1);
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_ident);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_let_tok] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym_toplevel] = STATE(2),
    [sym_decl] = STATE(5),
    [sym_expr] = STATE(5),
    [sym_apply] = STATE(14),
    [sym_concat] = STATE(11),
    [sym_factor] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_let_tok] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [sym_ident] = ACTIONS(9),
    [sym_string] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_toplevel] = STATE(3),
    [sym_decl] = STATE(5),
    [sym_expr] = STATE(5),
    [sym_apply] = STATE(14),
    [sym_concat] = STATE(11),
    [sym_factor] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_let_tok] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [sym_ident] = ACTIONS(9),
    [sym_string] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_toplevel] = STATE(3),
    [sym_decl] = STATE(5),
    [sym_expr] = STATE(5),
    [sym_apply] = STATE(14),
    [sym_concat] = STATE(11),
    [sym_factor] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_let_tok] = ACTIONS(15),
    [sym_number] = ACTIONS(18),
    [sym_ident] = ACTIONS(21),
    [sym_string] = ACTIONS(18),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      sym_ident,
    STATE(7), 1,
      sym_expr,
    STATE(11), 1,
      sym_concat,
    STATE(12), 1,
      sym_factor,
    STATE(14), 1,
      sym_apply,
    ACTIONS(7), 2,
      sym_number,
      sym_string,
  [20] = 2,
    ACTIONS(26), 1,
      sym_ident,
    ACTIONS(24), 4,
      ts_builtin_sym_end,
      sym_let_tok,
      sym_number,
      sym_string,
  [30] = 2,
    ACTIONS(30), 1,
      sym_ident,
    ACTIONS(28), 4,
      ts_builtin_sym_end,
      sym_let_tok,
      sym_number,
      sym_string,
  [40] = 2,
    ACTIONS(34), 1,
      sym_ident,
    ACTIONS(32), 4,
      ts_builtin_sym_end,
      sym_let_tok,
      sym_number,
      sym_string,
  [50] = 3,
    ACTIONS(9), 1,
      sym_ident,
    STATE(15), 1,
      sym_factor,
    ACTIONS(7), 2,
      sym_number,
      sym_string,
  [61] = 3,
    ACTIONS(9), 1,
      sym_ident,
    STATE(13), 1,
      sym_factor,
    ACTIONS(7), 2,
      sym_number,
      sym_string,
  [72] = 2,
    ACTIONS(38), 1,
      aux_sym_apply_token1,
    ACTIONS(36), 2,
      aux_sym_expr_token1,
      anon_sym_COMMA,
  [80] = 3,
    ACTIONS(40), 1,
      aux_sym_expr_token1,
    ACTIONS(42), 1,
      aux_sym_apply_token1,
    ACTIONS(44), 1,
      anon_sym_COMMA,
  [90] = 2,
    ACTIONS(48), 1,
      aux_sym_apply_token1,
    ACTIONS(46), 2,
      aux_sym_expr_token1,
      anon_sym_COMMA,
  [98] = 2,
    ACTIONS(52), 1,
      aux_sym_apply_token1,
    ACTIONS(50), 2,
      aux_sym_expr_token1,
      anon_sym_COMMA,
  [106] = 2,
    ACTIONS(54), 1,
      aux_sym_expr_token1,
    ACTIONS(56), 1,
      aux_sym_apply_token1,
  [113] = 2,
    ACTIONS(58), 1,
      aux_sym_expr_token1,
    ACTIONS(60), 1,
      aux_sym_apply_token1,
  [120] = 1,
    ACTIONS(62), 1,
      sym_ident,
  [124] = 1,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
  [128] = 1,
    ACTIONS(66), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 20,
  [SMALL_STATE(6)] = 30,
  [SMALL_STATE(7)] = 40,
  [SMALL_STATE(8)] = 50,
  [SMALL_STATE(9)] = 61,
  [SMALL_STATE(10)] = 72,
  [SMALL_STATE(11)] = 80,
  [SMALL_STATE(12)] = 90,
  [SMALL_STATE(13)] = 98,
  [SMALL_STATE(14)] = 106,
  [SMALL_STATE(15)] = 113,
  [SMALL_STATE(16)] = 120,
  [SMALL_STATE(17)] = 124,
  [SMALL_STATE(18)] = 128,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toplevel, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_toplevel, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 4, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decl, 4, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_apply, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_concat, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concat, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_concat, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concat, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_apply, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [64] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_calque(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "calque",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
