/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_let_tok = 1,
  anon_sym_EQ = 2,
  aux_sym_expression_token1 = 3,
  aux_sym_application_token1 = 4,
  anon_sym_COMMA = 5,
  sym_number = 6,
  sym_ident = 7,
  sym_string = 8,
  sym_comment = 9,
  sym_source_file = 10,
  sym_toplevel = 11,
  sym_decl = 12,
  sym_expression = 13,
  sym_application = 14,
  sym_concatenation = 15,
  sym_factor = 16,
  aux_sym_source_file_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_let_tok] = "let_tok",
  [anon_sym_EQ] = "=",
  [aux_sym_expression_token1] = "expression_token1",
  [aux_sym_application_token1] = "application_token1",
  [anon_sym_COMMA] = "operator",
  [sym_number] = "number",
  [sym_ident] = "ident",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_toplevel] = "toplevel",
  [sym_decl] = "decl",
  [sym_expression] = "expression",
  [sym_application] = "application",
  [sym_concatenation] = "concatenation",
  [sym_factor] = "factor",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_let_tok] = sym_let_tok,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_expression_token1] = aux_sym_expression_token1,
  [aux_sym_application_token1] = aux_sym_application_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_number] = sym_number,
  [sym_ident] = sym_ident,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_toplevel] = sym_toplevel,
  [sym_decl] = sym_decl,
  [sym_expression] = sym_expression,
  [sym_application] = sym_application,
  [sym_concatenation] = sym_concatenation,
  [sym_factor] = sym_factor,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_let_tok] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_application_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_toplevel] = {
    .visible = true,
    .named = true,
  },
  [sym_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym_concatenation] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '.') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(1);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_let_tok);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_application_token1);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(1);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_ident);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_let_tok] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym_toplevel] = STATE(2),
    [sym_decl] = STATE(5),
    [sym_expression] = STATE(5),
    [sym_application] = STATE(14),
    [sym_concatenation] = STATE(11),
    [sym_factor] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_let_tok] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [sym_ident] = ACTIONS(11),
    [sym_string] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_toplevel] = STATE(3),
    [sym_decl] = STATE(5),
    [sym_expression] = STATE(5),
    [sym_application] = STATE(14),
    [sym_concatenation] = STATE(11),
    [sym_factor] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_let_tok] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [sym_ident] = ACTIONS(11),
    [sym_string] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_toplevel] = STATE(3),
    [sym_decl] = STATE(5),
    [sym_expression] = STATE(5),
    [sym_application] = STATE(14),
    [sym_concatenation] = STATE(11),
    [sym_factor] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_let_tok] = ACTIONS(17),
    [sym_number] = ACTIONS(20),
    [sym_ident] = ACTIONS(23),
    [sym_string] = ACTIONS(20),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_ident,
    STATE(7), 1,
      sym_expression,
    STATE(11), 1,
      sym_concatenation,
    STATE(12), 1,
      sym_factor,
    STATE(14), 1,
      sym_application,
    ACTIONS(9), 2,
      sym_number,
      sym_string,
  [23] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(28), 1,
      sym_ident,
    ACTIONS(26), 4,
      ts_builtin_sym_end,
      sym_let_tok,
      sym_number,
      sym_string,
  [36] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      sym_ident,
    ACTIONS(30), 4,
      ts_builtin_sym_end,
      sym_let_tok,
      sym_number,
      sym_string,
  [49] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      sym_ident,
    ACTIONS(34), 4,
      ts_builtin_sym_end,
      sym_let_tok,
      sym_number,
      sym_string,
  [62] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_ident,
    STATE(15), 1,
      sym_factor,
    ACTIONS(9), 2,
      sym_number,
      sym_string,
  [76] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_ident,
    STATE(13), 1,
      sym_factor,
    ACTIONS(9), 2,
      sym_number,
      sym_string,
  [90] = 3,
    ACTIONS(40), 1,
      aux_sym_application_token1,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(38), 2,
      aux_sym_expression_token1,
      anon_sym_COMMA,
  [101] = 4,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(44), 1,
      aux_sym_expression_token1,
    ACTIONS(46), 1,
      aux_sym_application_token1,
    ACTIONS(48), 1,
      anon_sym_COMMA,
  [114] = 3,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(52), 1,
      aux_sym_application_token1,
    ACTIONS(50), 2,
      aux_sym_expression_token1,
      anon_sym_COMMA,
  [125] = 3,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(56), 1,
      aux_sym_application_token1,
    ACTIONS(54), 2,
      aux_sym_expression_token1,
      anon_sym_COMMA,
  [136] = 3,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(58), 1,
      aux_sym_expression_token1,
    ACTIONS(60), 1,
      aux_sym_application_token1,
  [146] = 3,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(62), 1,
      aux_sym_expression_token1,
    ACTIONS(64), 1,
      aux_sym_application_token1,
  [156] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_ident,
  [163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
  [170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 23,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 49,
  [SMALL_STATE(8)] = 62,
  [SMALL_STATE(9)] = 76,
  [SMALL_STATE(10)] = 90,
  [SMALL_STATE(11)] = 101,
  [SMALL_STATE(12)] = 114,
  [SMALL_STATE(13)] = 125,
  [SMALL_STATE(14)] = 136,
  [SMALL_STATE(15)] = 146,
  [SMALL_STATE(16)] = 156,
  [SMALL_STATE(17)] = 163,
  [SMALL_STATE(18)] = 170,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toplevel, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_toplevel, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 4, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decl, 4, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_concatenation, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concatenation, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_concatenation, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concatenation, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [68] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_calque(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "calque",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
